baseURL = "http://wtg-env.netlify.com"
languageCode = "fr"
title = "Site de WTG Environnement"

publishDir = "public"
theme = "hugo-creative-theme"
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "fr"
disableKinds = ["taxonomy","taxonomyTerm"]
enableRobotsTXT = true
googleAnalytics = ""

[params]
	name = "WTG Environnement"
	description = "Site officiel de WTG Environnement"

	# The path must be relative to the static folder
	favicon = "favicon.ico"

	# Navigation
	[params.navigation]
		brand = "WTG Environnement"

		[params.navigation.links]
			about     = "Qui sommes nous"
			services  = "Nos prestations"
			portfolio = "Nos références"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Le Forage Environnemental"
		subtitle   = "au service de vos projets"
		buttonText = "Découvrez tous nos services"

	# About section
	[params.about]
		headline    = "Qui sommes nous ?"
		description = "Située à Stattmatten (67), WTG-Environnement propose, depuis 2003, ses services dans les domaines du forage, de la géologie, de l'environnement et des travaux."
		#buttonText  = "Get started!"


	# Service section
	[params.services]
		headline = "Parmi nos principales prestations ..."

        [[params.services.list]]
            icon = "fa-eye"
            title = "Sondage de Reconnaissance"
            description = "WTG-Environnement est équipée de sondeuses sur chenilles Comacchio GEO 300 (3t) et GEO 305 (4,5t) permettant la réalisation de sondages de reconnaissance et la pose de piézomètres "

        [[params.services.list]]
			icon = "fa-sort-amount-asc"
			title = "Sondage carroté sous Gaine"
			description = "WTG-Environnement est équipée d'une sondeuse GEOPROBE 54 LT sur chenilles permettant la réalisation de sondages carottés sous gaine."

        [[params.services.list]]
            icon = "fa-tint"
            title = "Suivi de nappe et Pompage"
            description = "WTG-Environnement réalise des travaux de suivis de nappes, des pompages, des essais de pompage, des installations et démontages de pompes."

		[[params.services.list]]
            icon = "fa-building"
            title = "Sondage en intérieur"
            description = "WTG-Environnement est équipée d'un carottier portable à gouges lanternées et propose des sondages de reconnaissance légers jusqu'à 4-5 mètres environ. Le matériel électrique et portable permet de réaliser facilement des investigations à l'intérieur de bâtiments et dans des endroits difficiles d'accès."


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Notre plaquette détaillée"

		[params.aside.button]
			text = "Télécharger"
			link = "/documents/test.pdf"

	# Contact section
	[params.contact]
		headline = "Nous contacter ..."
		description = "Contactez nous dès maintenant pour obtenir un **devis gratuit** !"
		phone = "03 88 09 27 54"
		email = "wtg.env@gmail.com"

	# Google Maps section
	[params.location]
	 	latitude  = "48.793608"
	 	longitude = "8.006754"
	 	maps_api_key = ""
